# Generated by Django 2.2.7 on 2019-11-21 16:56

from django.db import migrations


def create_processors(apps, schema_editor) -> None:
    """
    Creates processors to populate database.
    """
    Processor = apps.get_model("api", "Processor")
    [
        Processor(
            processor_description="Intel Core i5", processor_brand="Intel"
        ).save(),
        Processor(
            processor_description="Intel Core i7", processor_brand="Intel"
        ).save(),
        Processor(
            processor_description="AMD Ryzen 7", processor_brand="AMD"
        ).save(),
        Processor(
            processor_description="AMD Athlon", processor_brand="AMD"
        ).save(),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_processors)]
