# Generated by Django 2.2.7 on 2019-11-21 18:02

from django.db import migrations


def create_memories(apps, schema_editor) -> None:
    """
    Create memories to populate database.
    """
    Memory = apps.get_model("api", "Memory")
    [
        Memory(ram_description="Hiper X", ram_size=4).save(),
        Memory(ram_description="Hiper X", ram_size=4).save(),
        Memory(ram_description="Hiper X", ram_size=8).save(),
        Memory(ram_description="Hiper X", ram_size=8).save(),
        Memory(ram_description="Hiper X", ram_size=16).save(),
        Memory(ram_description="Hiper X", ram_size=16).save(),
        Memory(ram_description="Hiper X", ram_size=32).save(),
        Memory(ram_description="Hiper X", ram_size=32).save(),
        Memory(ram_description="Hiper X", ram_size=64).save(),
        Memory(ram_description="Hiper X", ram_size=64).save(),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20191121_1458"),
    ]

    operations = [migrations.RunPython(create_memories)]
