version: '2.3'

services:
  angular:
    hostname: localhost
    container_name: angular-container
    build: .
    ports:
      - 4200:4200
    command:
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"