version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py test api.tests && python manage.py runserver 0.0.0.0:8000"
    container_name: silvertec
    volumes:
      - .:/silvertec
    ports:
      - "8000:8000"