# Generated by Django 2.2.7 on 2019-11-21 18:02

from django.db import migrations


def create_memories(apps, schema_editor):
    Memory = apps.get_model("api", "Memory")
    [
        Memory(1, ram_description="Hiper X", ram_size=4).save(),
        Memory(2, ram_description="Hiper X", ram_size=4).save(),
        Memory(3, ram_description="Hiper X", ram_size=8).save(),
        Memory(4, ram_description="Hiper X", ram_size=8).save(),
        Memory(5, ram_description="Hiper X", ram_size=16).save(),
        Memory(6, ram_description="Hiper X", ram_size=16).save(),
        Memory(7, ram_description="Hiper X", ram_size=32).save(),
        Memory(8, ram_description="Hiper X", ram_size=32).save(),
        Memory(9, ram_description="Hiper X", ram_size=64).save(),
        Memory(10, ram_description="Hiper X", ram_size=64).save(),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20191121_1458"),
    ]

    operations = [migrations.RunPython(create_memories)]
