# Generated by Django 2.2.7 on 2019-11-21 18:02

from django.db import migrations


def create_memories(apps, schema_editor):
    Memory = apps.get_model("api", "Memory")
    ram1 = Memory(1, ram_description="Hiper X", ram_size=4)
    ram2 = Memory(2, ram_description="Hiper X", ram_size=4)
    ram3 = Memory(3, ram_description="Hiper X", ram_size=8)
    ram4 = Memory(4, ram_description="Hiper X", ram_size=8)
    ram5 = Memory(5, ram_description="Hiper X", ram_size=16)
    ram6 = Memory(6, ram_description="Hiper X", ram_size=16)
    ram7 = Memory(7, ram_description="Hiper X", ram_size=32)
    ram8 = Memory(8, ram_description="Hiper X", ram_size=32)
    ram9 = Memory(9, ram_description="Hiper X", ram_size=64)
    ram10 = Memory(10, ram_description="Hiper X", ram_size=64)

    memories_list = [ram1, ram2, ram3, ram4, ram5, ram6, ram7, ram8, ram9, ram10]
    [memory.save() for memory in memories_list]


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20191121_1458"),
    ]

    operations = [migrations.RunPython(create_memories)]
