# Generated by Django 2.2.7 on 2019-11-23 14:05

from django.db import migrations
from django.contrib.auth.models import User


def create_super_user(apps, schema_editor):
    """
    Create a sample super user to demonstrate the API using with docker.
    """
    User.objects.create_superuser(username='intmed', password='intmed', email='intmed@intmed.com')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191121_1505'),
    ]

    operations = [
        migrations.RunPython(create_super_user)
    ]
